services:
  redis:
    image: "redis:6.2.10"
    ports:
      - "6379:6379"
  postgres:
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"