name: publish

on:
  push:
    branches: [ dev ]

jobs:
  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Resetting git to dev
        run: git reset --hard dev

      - name: Resetting git to dev
        run: git fetch --tags || true

      - name: Install poetry
        run: python -m pip install poetry

      - name: Install requirements
        run: poetry install

      - name: Publishing to pypi
        run: poetry publish --build --skip-existing --no-interaction
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}