name: publish

on:
  push:
    branches: [ main ]

jobs:
  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Resetting git to main
        run: git reset --hard main

      - name: Resetting git to main
        run: git fetch --tags || true

      - name: Install uv
        run: python -m pip install uv

      - name: Publishing to pypi
        run: |
          uv build
          uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}